# Generated by Django 4.1.3 on 2022-11-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
