# Generated by Django 4.1.3 on 2022-11-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_subcategory'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
