# Generated by Django 4.1.3 on 2022-12-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact-Us', 'verbose_name_plural': 'Contact-Us'},
        ),
    ]
