# Generated by Django 4.1.3 on 2022-11-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_white',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
