# Generated by Django 4.1.3 on 2022-11-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesetting_logo_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='short_footer_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
