# Generated by Django 4.1.3 on 2022-11-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_sitesetting_short_footer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='shop_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
