# Generated by Django 4.1.3 on 2022-11-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
