# Generated by Django 4.1.3 on 2022-11-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Check this for 'Active'"),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Check this for 'Active'"),
        ),
    ]
