# Generated by Django 4.1.3 on 2022-11-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_subcategory'),
        ('products', '0005_product_is_active_productimage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand'),
        ),
    ]
